apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: base-to-base-wait-copy
spec:
  host: base-to-base-wait-copy
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---
