apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: base-to-base-wait-copy-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - base-to-base-wait-copybffp.zhuge.com
    - port:
        name: grpc
        number: 50051
        protocol: HTTP
      hosts:
        - base-to-base-wait-copybffp.zhuge.com

