kind: Service
apiVersion: v1
metadata:
  name: origin
  labels:
    app: origin
spec:
  selector:
    app: origin
  ports:
    - port: 80
      name: http-port
      protocol: TCP
      targetPort: 80

    - port: 50051
      name: grpc-port
      protocol: TCP
      targetPort: 50051