apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: visource
spec:
  host: visource
  subsets:
    - name: v2
      labels:
        version: v2
    - name: v1
      labels:
        version: v1
---